Entity\UserFieldValues:
  type: entity
  table: user_field_values
  repositoryClass: Entity\Repository\UserFieldValuesRepository
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: IDENTITY
    user_id:
      type: integer
      unsigned: false
      nullable: false
    field_id:
      type: integer
      unsigned: false
      nullable: false
    field_value:
      type: text
      nullable: true
    tms:
      type: datetime
      nullable: false
  lifecycleCallbacks:
    prePersist:
      - before_save
